[mcp_servers.21st]
url = "https://21st.dev/api/mcp"

[mcp_servers.21st.http_headers]
x-api-key = "21st_sk_cab4d00ad89c022ab5125238a39091437f0b679236fd93d88c83146cb2ce6635"

[mcp_servers.context7]
command = "npx"
args = [
    "-y",
    "@upstash/context7-mcp",
]

[mcp_servers.playwright]
command = "npx"
args = [
    "-y",
    "@playwright/mcp",
]
