/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed-variant": "#5516be",
        "surface-container-high": "#232a34",
        "primary-fixed-dim": "#c3c0ff",
        "on-tertiary-container": "#93e8ff",
        "on-secondary": "#3c0091",
        "secondary-fixed-dim": "#d0bcff",
        "inverse-primary": "#4d44e3",
        "tertiary": "#4cd7f6",
        "background": "#0d141d",
        "outline": "#918fa1",
        "on-primary": "#1d00a5",
        "tertiary-fixed-dim": "#4cd7f6",
        "on-tertiary-fixed": "#001f26",
        "on-secondary-container": "#c4abff",
        "surface": "#0d141d",
        "primary": "#c3c0ff",
        "secondary-container": "#571bc1",
        "on-primary-fixed-variant": "#3323cc",
        "on-tertiary-fixed-variant": "#004e5c",
        "surface-variant": "#2e353f",
        "outline-variant": "#464555",
        "error": "#ffb4ab",
        "surface-container": "#192029",
        "inverse-on-surface": "#2a313b",
        "tertiary-container": "#006a7c",
        "surface-dim": "#0d141d",
        "on-surface-variant": "#c7c4d8",
        "primary-container": "#4f46e5",
        "surface-bright": "#333a44",
        "error-container": "#93000a",
        "secondary-fixed": "#e9ddff",
        "on-primary-container": "#dad7ff",
        "tertiary-fixed": "#acedff",
        "on-tertiary": "#003640",
        "on-primary-fixed": "#0f0069",
        "surface-container-low": "#151c25",
        "on-surface": "#dce3f0",
        "primary-fixed": "#e2dfff",
        "on-background": "#dce3f0",
        "surface-container-lowest": "#080f17",
        "on-error-container": "#ffdad6",
        "on-error": "#690005",
        "surface-container-highest": "#2e353f",
        "secondary": "#d0bcff",
        "inverse-surface": "#dce3f0",
        "surface-tint": "#c3c0ff",
        "on-secondary-fixed": "#23005c"
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px"
      },
      spacing: {
        "stack-md": "16px",
        "stack-lg": "32px",
        "margin-mobile": "16px",
        "margin-desktop": "40px",
        "unit": "4px",
        "gutter": "24px",
        "stack-sm": "8px",
        "container-max": "1280px"
      },
      fontFamily: {
        "headline-lg": ["Geist"],
        "body-sm": ["Geist"],
        "body-lg": ["Geist"],
        "label-sm": ["JetBrains Mono"],
        "headline-md": ["Geist"],
        "label-md": ["JetBrains Mono"],
        "headline-lg-mobile": ["Geist"],
        "body-md": ["Geist"],
        "display": ["Geist"],
        "title-lg": ["Geist"]
      },
      fontSize: {
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "500" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.02em", fontWeight: "500" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "display": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "title-lg": ["20px", { lineHeight: "28px", fontWeight: "500" }]
      }
    },
  },
  plugins: [],
}
