/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      fontFamily: {
        sans: ["Geist", "system-ui", "-apple-system", "sans-serif"],
        display: ["Geist", "system-ui", "sans-serif"],
        mono: ["JetBrains Mono", "ui-monospace", "monospace"],
      },
      colors: {
        primary: "#003927",
        "on-primary": "#ffffff",
        "primary-container": "#00523a",
        "on-primary-container": "#80c4a5",
        "primary-fixed": "#acf1d0",
        "primary-fixed-dim": "#90d5b5",
        "on-primary-fixed": "#002115",
        "on-primary-fixed-variant": "#00513a",
        "inverse-primary": "#90d5b5",

        secondary: "#9a4600",
        "on-secondary": "#ffffff",
        "secondary-container": "#fe924e",
        "on-secondary-container": "#321200",
        "secondary-fixed": "#ffdbc9",
        "secondary-fixed-dim": "#ffb68c",
        "on-secondary-fixed": "#321200",
        "on-secondary-fixed-variant": "#753400",

        tertiary: "#04382b",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#214f41",
        "on-tertiary-container": "#90c0ae",
        "tertiary-fixed": "#bcedda",
        "tertiary-fixed-dim": "#a1d1be",
        "on-tertiary-fixed": "#002118",
        "on-tertiary-fixed-variant": "#214f41",

        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",

        background: "#f9f9f9",
        "on-background": "#1a1c1c",
        surface: "#f9f9f9",
        "on-surface": "#1a1c1c",
        "surface-variant": "#e2e2e2",
        "on-surface-variant": "#3f4944",
        "surface-dim": "#dadada",
        "surface-bright": "#f9f9f9",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f3f3f3",
        "surface-container": "#eeeeee",
        "surface-container-high": "#e8e8e8",
        "surface-container-highest": "#e2e2e2",
        "surface-tint": "#256a50",

        outline: "#707973",
        "outline-variant": "#bfc9c2",
        "inverse-surface": "#2f3131",
        "inverse-on-surface": "#f1f1f1",
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
      spacing: {
        unit: "8px",
        gutter: "24px",
        "section-gap": "80px",
        "container-padding-mobile": "20px",
        "container-padding-desktop": "40px",
        "max-width": "1280px",
        "stack-sm": "8px",
        "stack-md": "16px",
        "stack-lg": "32px",
        "margin-mobile": "16px",
        "margin-desktop": "40px",
        "container-max": "1280px",
      },
      fontSize: {
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.04em", fontWeight: "600" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.02em", fontWeight: "500" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "display-lg-mobile": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "700" }],
        code: ["14px", { lineHeight: "22px", fontWeight: "400" }],
      },
      maxWidth: {
        "max-width": "1280px",
      },
    },
  },
  plugins: [],
}
