"""add_ai_preferences_and_message_fields

Revision ID: b691863bf206
Revises: 49613b65afd3
Create Date: 2026-07-29 01:33:54.028613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b691863bf206'
down_revision: Union[str, Sequence[str], None] = '49613b65afd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_ai_preferences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('mode', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_user_ai_preferences_id'), 'user_ai_preferences', ['id'], unique=False)
    op.add_column('messages', sa.Column('provider', sa.String(), nullable=True))
    op.add_column('messages', sa.Column('model_used', sa.String(), nullable=True))
    op.add_column('messages', sa.Column('latency_ms', sa.Integer(), nullable=True))
    op.add_column('messages', sa.Column('tokens', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'tokens')
    op.drop_column('messages', 'latency_ms')
    op.drop_column('messages', 'model_used')
    op.drop_column('messages', 'provider')
    op.drop_index(op.f('ix_user_ai_preferences_id'), table_name='user_ai_preferences')
    op.drop_table('user_ai_preferences')
    # ### end Alembic commands ###
