from enum import Enum

class RouterEventType(str, Enum):
    MODEL_DISCOVERED = "MODEL_DISCOVERED"
    MODEL_PROFILED = "MODEL_PROFILED"
    BENCHMARK_COMPLETED = "BENCHMARK_COMPLETED"
    MODEL_HEALTH_CHANGED = "MODEL_HEALTH_CHANGED"
    REQUEST_STARTED = "REQUEST_STARTED"
    REQUEST_FINISHED = "REQUEST_FINISHED"
    VALIDATION_FAILED = "VALIDATION_FAILED"
